server:
  port : 8082

  # Database configuration
spring:
  application:
    name: "item"
  datasource:
    url: jdbc:mysql://localhost:3306/fassciodb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password:
    password: ENC(6T8Jg2gtPJ6QHL0Axx5eIbDm/ZllZNryUg0SMu16TMgyIUMnwDuGdj9MPQSyytW0)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

